application:
  security:
    jwt:
        jwt-expiration-in-days: 7
        secret-key: FZ3"p'Hg#N<v)QNsk+h7T4sq7`a1;5kL7_sD5`
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/solides
      username: admin
      password: desafio
      driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
